# Generated by Django 4.2.23 on 2025-12-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("livros", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="livro",
            name="data_aquisicao",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Aquisição"
            ),
        ),
    ]
